from __future__ import annotations

ROLE_PERMISSIONS: dict[str, set[str]] = {
    "owner": {
        "venues.read",
        "venues.update",
        "rooms.read",
        "rooms.create",
        "rooms.update",
        "rooms.delete",
        "seats.read",
        "seats.create",
        "seats.update",
        "seats.delete",
        "features.read",
        "feature_links.read",
        "feature_links.link",
        "feature_links.unlink",
        "booking_rules.read",
        "booking_rules.update",
        "room_hours.read",
        "room_hours.update",
        "tariffs.read",
        "tariffs.create",
        "tariffs.update",
        "tariffs.archive",
        "availability.read",
        "holds.create",
        "holds.cancel",
        "bookings.create",
        "bookings.read",
        "bookings.cancel",
        "bookings.update_status",
        "checkins.create",
        "transactions.read",
        "transactions.capture",
        "transactions.refund",
        "analytics.read",
        "notifications.read",
        "notifications.send",
        "notification_prefs.read",
        "notification_prefs.update",
        "users.read",
        "roles.assign",
        "roles.revoke",
        "invites.create",
        "invites.read",
        "invites.revoke",
    },
    "admin": {
        "venues.read",
        "venues.update",
        "rooms.read",
        "rooms.create",
        "rooms.update",
        "rooms.delete",
        "seats.read",
        "seats.create",
        "seats.update",
        "seats.delete",
        "features.read",
        "feature_links.read",
        "feature_links.link",
        "feature_links.unlink",
        "booking_rules.read",
        "booking_rules.update",
        "room_hours.read",
        "room_hours.update",
        "tariffs.read",
        "tariffs.create",
        "tariffs.update",
        "tariffs.archive",
        "availability.read",
        "holds.create",
        "holds.cancel",
        "bookings.create",
        "bookings.read",
        "bookings.cancel",
        "bookings.update_status",
        "checkins.create",
        "analytics.read",
        "notifications.read",
        "notifications.send",
        "notification_prefs.read",
        "notification_prefs.update",
        "users.read",
        "roles.assign",
        "roles.revoke",
        "invites.create",
        "invites.read",
        "invites.revoke",
    },
    "manager": {
        "venues.read",
        "rooms.read",
        "rooms.update",
        "seats.read",
        "seats.update",
        "features.read",
        "feature_links.read",
        "room_hours.read",
        "availability.read",
        "holds.create",
        "holds.cancel",
        "bookings.create",
        "bookings.read",
        "bookings.cancel",
        "bookings.update_status",
        "checkins.create",
        "analytics.read",
        "notifications.read",
        "notification_prefs.read",
    },
    "support": {
        "venues.read",
        "rooms.read",
        "seats.read",
        "features.read",
        "availability.read",
        "bookings.read",
        "notifications.read",
        "users.read",
        "invites.read",
    },
    "billing": {
        "transactions.read",
        "transactions.capture",
        "transactions.refund",
        "analytics.read",
        "bookings.read",
        "users.read",
    },
    "auditor": {
        "venues.read",
        "rooms.read",
        "seats.read",
        "features.read",
        "availability.read",
        "bookings.read",
        "transactions.read",
        "analytics.read",
        "notifications.read",
        "users.read",
    },
    "client": {
        "availability.read",
        "holds.create",
        "holds.cancel",
        "bookings.create",
        "bookings.read",
        "bookings.cancel",
        "checkins.create",
        "notification_prefs.read",
        "notification_prefs.update",
    },
}

ROLE_NAMES: dict[str, str] = {
    "owner": "Owner",
    "admin": "Admin",
    "manager": "Manager",
    "support": "Support",
    "billing": "Billing",
    "auditor": "Auditor",
    "client": "Client",
}


def all_permissions() -> list[str]:
    return sorted({permission for permissions in ROLE_PERMISSIONS.values() for permission in permissions})
